HTTP/1.0 200 OK
Content-Type:text/xml

<?xml version="1.0" standalone="yes" ?><!DOCTYPE SHOUTCASTSERVER [<!ELEMENT SHOUTCASTSERVER (CURRENTLISTENERS,PEAKLISTENERS,MAXLISTENERS,REPORTEDLISTENERS,AVERAGETIME,SERVERGENRE,SERVERURL,SERVERTITLE,SONGTITLE,SONGURL,IRC,ICQ,AIM,WEBHITS,STREAMHITS,STREAMSTATUS,BITRATE,CONTENT,VERSION,WEBDATA,LISTENERS,SONGHISTORY)><!ELEMENT CURRENTLISTENERS (#PCDATA)><!ELEMENT PEAKLISTENERS (#PCDATA)><!ELEMENT MAXLISTENERS (#PCDATA)><!ELEMENT REPORTEDLISTENERS (#PCDATA)><!ELEMENT AVERAGETIME (#PCDATA)><!ELEMENT SERVERGENRE (#PCDATA)><!ELEMENT SERVERURL (#PCDATA)><!ELEMENT SERVERTITLE (#PCDATA)><!ELEMENT SONGTITLE (#PCDATA)><!ELEMENT SONGURL (#PCDATA)><!ELEMENT IRC (#PCDATA)><!ELEMENT ICQ (#PCDATA)><!ELEMENT AIM (#PCDATA)><!ELEMENT WEBHITS (#PCDATA)><!ELEMENT STREAMHITS (#PCDATA)><!ELEMENT STREAMSTATUS (#PCDATA)><!ELEMENT BITRATE (#PCDATA)><!ELEMENT CONTENT (#PCDATA)><!ELEMENT VERSION (#PCDATA)><!ELEMENT WEBDATA (INDEX,LISTEN,PALM7,LOGIN,LOGINFAIL,PLAYED,COOKIE,ADMIN,UPDINFO,KICKSRC,KICKDST,UNBANDST,BANDST,VIEWBAN,UNRIPDST,RIPDST,VIEWRIP,VIEWXML,VIEWLOG,INVALID)><!ELEMENT INDEX (#PCDATA)><!ELEMENT LISTEN (#PCDATA)><!ELEMENT PALM7 (#PCDATA)><!ELEMENT LOGIN (#PCDATA)><!ELEMENT LOGINFAIL (#PCDATA)><!ELEMENT PLAYED (#PCDATA)><!ELEMENT COOKIE (#PCDATA)><!ELEMENT ADMIN (#PCDATA)><!ELEMENT UPDINFO (#PCDATA)><!ELEMENT KICKSRC (#PCDATA)><!ELEMENT KICKDST (#PCDATA)><!ELEMENT UNBANDST (#PCDATA)><!ELEMENT BANDST (#PCDATA)><!ELEMENT VIEWBAN (#PCDATA)><!ELEMENT UNRIPDST (#PCDATA)><!ELEMENT RIPDST (#PCDATA)><!ELEMENT VIEWRIP (#PCDATA)><!ELEMENT VIEWXML (#PCDATA)><!ELEMENT VIEWLOG (#PCDATA)><!ELEMENT INVALID (#PCDATA)><!ELEMENT LISTENERS (LISTENER*)><!ELEMENT LISTENER (HOSTNAME,USERAGENT,UNDERRUNS,CONNECTTIME, POINTER, UID)><!ELEMENT HOSTNAME (#PCDATA)><!ELEMENT USERAGENT (#PCDATA)><!ELEMENT UNDERRUNS (#PCDATA)><!ELEMENT CONNECTTIME (#PCDATA)><!ELEMENT POINTER (#PCDATA)><!ELEMENT UID (#PCDATA)><!ELEMENT SONGHISTORY (SONG*)><!ELEMENT SONG (PLAYEDAT, TITLE)><!ELEMENT PLAYEDAT (#PCDATA)><!ELEMENT TITLE (#PCDATA)>]><SHOUTCASTSERVER><CURRENTLISTENERS>1</CURRENTLISTENERS><PEAKLISTENERS>100</PEAKLISTENERS><MAXLISTENERS>100</MAXLISTENERS><REPORTEDLISTENERS>1</REPORTEDLISTENERS><AVERAGETIME>558</AVERAGETIME><SERVERGENRE>Techno/Alterntive/Emo [--- lol</SERVERGENRE><SERVERURL>Http://711Clan.Net</SERVERURL><SERVERTITLE>Trollz0rs: MuSic FrOm UnDeR ThE bRidge</SERVERTITLE><SONGTITLE>KoRn - Alone I Break</SONGTITLE><SONGURL>www.doc.711clan.net</SONGURL><IRC>#711</IRC><ICQ>N/A</ICQ><AIM>N/A</AIM><WEBHITS>1336841</WEBHITS><STREAMHITS>60680</STREAMHITS><STREAMSTATUS>0</STREAMSTATUS><BITRATE>128</BITRATE><CONTENT>audio/mpeg</CONTENT><VERSION>1.9.8</VERSION><WEBDATA><INDEX>14862</INDEX><LISTEN>955</LISTEN><PALM7>10</PALM7><LOGIN>0</LOGIN><LOGINFAIL>185</LOGINFAIL><PLAYED>809622</PLAYED><COOKIE>12</COOKIE><ADMIN>259</ADMIN><UPDINFO>27955</UPDINFO><KICKSRC>13</KICKSRC><KICKDST>0</KICKDST><UNBANDST>2</UNBANDST><BANDST>2</BANDST><VIEWBAN>17</VIEWBAN><UNRIPDST>0</UNRIPDST><RIPDST>0</RIPDST><VIEWRIP>5</VIEWRIP><VIEWXML>482193</VIEWXML><VIEWLOG>12</VIEWLOG><INVALID>553</INVALID></WEBDATA><LISTENERS><LISTENER><HOSTNAME>207.200.98.1</HOSTNAME><USERAGENT>SHOUTcast Directory Tester</USERAGENT><UNDERRUNS>0</UNDERRUNS><CONNECTTIME>348127</CONNECTTIME><POINTER>0</POINTER><UID>60413</UID></LISTENER></LISTENERS><SONGHISTORY><SONG><PLAYEDAT>1274839622</PLAYEDAT><TITLE>KoRn - Alone I Break</TITLE></SONG><SONG><PLAYEDAT>1274839290</PLAYEDAT><TITLE>0 - Stone Temple Pilots - Half the man I used to be.MP3</TITLE></SONG><SONG><PLAYEDAT>1274839284</PLAYEDAT><TITLE>Marcy Playground - Opium</TITLE></SONG><SONG><PLAYEDAT>1274839122</PLAYEDAT><TITLE>Nirvana - Heart Shaped Box</TITLE></SONG><SONG><PLAYEDAT>1274838935</PLAYEDAT><TITLE>Marcy Playground - Opium</TITLE></SONG><SONG><PLAYEDAT>1274838656</PLAYEDAT><TITLE>Nirvana - Heart Shaped Box</TITLE></SONG><SONG><PLAYEDAT>1274838469</PLAYEDAT><TITLE>Marcy Playground - Opium</TITLE></SONG><SONG><PLAYEDAT>1274838188</PLAYEDAT><TITLE>Nirvana - Heart Shaped Box</TITLE></SONG><SONG><PLAYEDAT>1274838001</PLAYEDAT><TITLE>Marcy Playground - Opium</TITLE></SONG><SONG><PLAYEDAT>1274837721</PLAYEDAT><TITLE>Nirvana - Heart Shaped Box</TITLE></SONG></SONGHISTORY></SHOUTCASTSERVER>